# Generated by Django 3.2.4 on 2021-06-11 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='complete',
        ),
    ]
