# Generated by Django 3.2.4 on 2021-06-11 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_description_task_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='complete',
            new_name='completed',
        ),
    ]
